### ISSUE TITLE
Extract lists into individual json files

### ISSUE THREAD

**Issue by octoshrimpy** [octoshrimpy/boredom-remover-9000#6]
Extract json lists from within .js and into their own .json file for better 3rd party parsing (FLOSS mindset)

**Comment by Jisan129** [comment]
Can I try this?

**Comment by octoshrimpy** [comment]
@Jisan129 This one has already been taken care of, however #4 could still use some work if you'd like to tackle that one. As they stand, the toggles are hardcoded, and could use some abstracting out, in case new categories happen to be added. :)
